schema_version: 1

context:
  version: 4.0.3

package:
  name: r-bimets
  version: ${{ version }}

source:
  url: https://cran.r-project.org/src/contrib/bimets_${{ version }}.tar.gz
  sha256: 5e1940a1b986ff04e472d2011286aa52b531dc0ad09e431c3292a46992e2569c

build:
  noarch: generic
  number: 1
  script: R CMD INSTALL --build .

requirements:
  host:
    - r-base >=4.0
    - r-xts
    - r-zoo
  run:
    - r-base >=4.0
    - r-xts
    - r-zoo

tests:
  - script:
      - Rscript -e 'library("bimets")'

about:
  homepage: https://github.com/andrea-luciani/bimets
  summary: Time Series and Econometric Modeling
  description: |-
    Time series analysis, (dis)aggregation and manipulation,
    e.g. time series extension, merge, projection, lag, lead,
    delta, moving and cumulative average and product, selection by
    index, date and year-period, conversion to daily, monthly,
    quarterly, (semi)annually. Simultaneous equation models
    definition, estimation, simulation and forecasting with
    coefficient restrictions, error autocorrelation, exogenization,
    add-factors, impact and interim multipliers analysis,
    conditional equation evaluation, rational expectations,
    endogenous targeting and model renormalization, structural
    stability, stochastic simulation and forecast, optimal control.
  license: GPL-3.0-only
  license_file: inst/License_GPL-3.txt
  repository: https://github.com/cran/bimets

extra:
  recipe-maintainers:
    - dhirschfeld
